shellEmulator: true

trustPolicy: no-downgrade

packages:
  - 'packages/*'
  - example

catalogs:
  build:
    '@types/node': ^25.3.0
    bumpp: ^10.4.1
    tsdown: ^0.20.3
    tsx: ^4.19.4
    typescript: ^5.9.3
  lint:
    '@antfu/eslint-config': ^7.4.3
    eslint: ^10.0.1
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  runtime:
    defu: ^6.1.4
    dnum: ^2.17.0
  test:
    '@vitest/coverage-v8': ^4.0.18
    vite-tsconfig-paths: ^6.1.1
    vitest: ^4.0.18
